import { type Session } from "next-auth";
import Head from "next/head";
import { SessionProvider, useSession } from "next-auth/react";
import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Sidebar from "~/components/ui/Sidebar";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Mental Messanger</title>
        <meta name="description" content="Generated by BartoszJakubovsky" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex justify-center bg-blue-300 dark:bg-indigo-900 dark:text-gray-200  ">
        <Sidebar/>
        <Component {...pageProps} />
      </main>
    </SessionProvider>
  );
};
export default api.withTRPC(MyApp);
